name: Newsletter

on:
  workflow_dispatch:

jobs:
  build:
    name: Get Latest items
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: yarn install
      - name: Show Lastest Resources
        run: yarn newsletter
