name: Tweet Lastest Resources

on:
  schedule:
    - cron: "30 14 * * 3"
  workflow_dispatch:

jobs:
  build:
    name: Lastest Resources
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn latest:resources
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
          ISSUES_GITHUB_TOKEN: ${{ secrets.ISSUES_GITHUB_TOKEN }}
